
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicalapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medicalapp
  template: 
    metadata: # Dictionary
      name: medicalapp-pod
      labels: # Dictionary 
        app: medicalapp         
    spec:
      containers: # List
        - name: myapprep-container
          image: rambabut/myweb:v1.0.0
          ports:
            - containerPort: 80
