apiVersion: v1 # String
kind: Pod  # String
metadata: # Dictionary
  name: medicalapp-pod
  labels: # Dictionary 
    app: medicalapp         
spec:
  containers: # List
    - name: medicalapp
      image: rambabut/myweb:v1.0.0
      ports:
        - containerPort: 80
