apiVersion: v1
kind: Service
metadata:
  name: replicaset-nodeport-service
spec:
  type: NodePort
  selector:
    app: medicalapp_replica
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31232  
